  main:
    - identifier: about
      name: About
      url: /about
      weight: 100
    - identifier: contact
      name: Contact
      url: /contact
      weight: 200
    - identifier: markdown
      name: Markdown
      url: /markdown
      weight: 300
